site_name: Egopposer
site_url: https://line2345.github.io
site_author: line2345

# 仓库
repo_name: line2345.github.io
repo_url: https://github.com/line2345/line2345.github.io

theme:

  name: material

  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/link
      name: 关闭自动模式
  #primary: blue grey
  - media: "(prefers-color-scheme: light)"
    scheme: default # 日间模式
    primary: blue grey # 上方的
    accent: blue # 链接等可交互元件的高亮色
    # teal
    toggle:
      icon: material/toggle-switch # 图标
      name: 切换至夜间模式 # 鼠标悬浮提示
  - media: "(prefers-color-scheme: dark)"
    scheme: slate # 夜间模式
    primary: black
    accent: indigo
    # teal
    toggle:
      icon: material/toggle-switch-off-outline
      name: 切换至日间模式
  


  features:
    - navigation.top  # 启用顶部导航
    - navigation.tabs # 可选：如果有子级内容，可以将其显示为标签式导航

# 导航页
nav:
  - 首页: index.md
  - 转专业指南: 
    - part1: project1.md
  - 往年试题:
    - 深度学习: recall/重大软院-深度学习-24试题回忆.md
    - 机器学习: recall/重大软院-机器学习-24试题回忆.md

markdown_extensions:
  - tables # 表格支持
  - footnotes # 数学库支持
  - pymdownx.arithmatex:
      generic: true

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css